### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by Ngob**
Changing dependency on zend-stratigility to 2.0; allowing splash 8.2 to work.

### CODE REVIEW

**Comment by moufmouf** [comment]
In Stratigility 2, error middlewares are completely deprecated.

Therefore, you should remove those lines from the service provider: https://github.com/thecodingmachine/stratigility-harmony/blob/1.0/src/StratigilityServiceProvider.php#L52-L57

**Review by moufmouf — CHANGES_REQUESTED** [review]
In Stratigility 2, error middlewares are completely deprecated.

Therefore, you should remove those lines from the service provider: https://github.com/thecodingmachine/stratigility-harmony/blob/1.0/src/StratigilityServiceProvider.php#L52-L57

**Comment by Ngob** [comment]
Might we maintain MiddlewareOrder and MiddlewareListServiceProvider to remove ErrorMiddleware tactic?

**Comment by moufmouf** [comment]
@Ngob :+1: we indeed need to publish a new major release of https://github.com/thecodingmachine/middleware-list-universal-module with removed stratigility specific error middlewares

**Comment by moufmouf** [comment]
Done in 2.0

**Pull request closed without merging**
